### ISSUE TITLE
Problems with the WEC simulator?

### ISSUE THREAD

**Issue by ttosdevin** [DTOcean/dtocean#23]
Hi,

The error below occurred in the WEC simulator whilst I was following the video tutorial ‘Tutorial 2 #&#xfeff;1 Hydrodynamics’ once the add body description was clicked. All the inputs used were the same as those from the tutorial video. The mesh file I used was from the dtocean heaving_cylinder folder taken from: 
C:\Users\dtocean\data\dtocean_wec\wec_db\heaving_cylinder\cylinder.gdf 

I have tried with other mesh files also and the same error message appears.
Any help would be much appreciated, thanks.
 
![image](https://user-images.githubusercontent.com/40267513/41418532-cef254d0-6fe7-11e8-9982-f8c03cd6e2a7.png)

**Comment by H0R5E** [comment]
Hi, thanks for the bug report. I'll have a look at it, but I'm afraid this won't be fixed until the next version release. 

Watch this space.

Mat

**Comment by ttosdevin** [comment]
Hi,

Thanks for getting back to me so quickly, do you know roughly when the next
versin release is likely to be? I am currently completing my masters
disertation and was planning on using DTOcean but will change my plans if
the release is not in the next month.

Kind regards,
Tom

**Comment by H0R5E** [comment]
Hi Tom, no it's not planned to be that soon, I think it will be sometime in the autumn.

Mat

**Comment by H0R5E** [comment]
Fixed in development branch.
