### ISSUE TITLE
Installing DTOcean 2.0 (wizard based) alongside DTOcean 1.0 (Anaconda)

### ISSUE THREAD

**Issue by NoorvVelzen** [DTOcean/dtocean#31]
Hi!
I’m currently at the point of installing DTOcean2.0 on my computer. I went through the video how to install this latest version.
I came across an issue: I have DTOcean(1.0) installed on my computer through anaconda, therefore, uninstalling DTOcean(1.0) is not as straightforward as shown in your video. 
Can I install DTOcean2.0 when DTOcean(1.0) is still installed on my computer? Or would it interfere with the new version?
Thanks!

**Comment by H0R5E** [comment]
Can you give me some more details?

Did you attempt to install DTOcean 2? If so, using which method and what was the problem you encountered?

What end state do you want? Do you want to keep your anaconda DTOcean 1.0 and install the wizard version of 2.0 alongside or do you want to update the anaconda version to 2.0? Or something else?

**Comment by NoorvVelzen** [comment]
Hi,
As it was indicated in the installation video to uninstall DTOcean1.0. I did not install DTOcean2.0 before uninstalling DTOcean1.0, which is not as straightforward on my computer (anaconda DTOcean1.0) as in the video.
Regarding the wished for end stage, I want to install DTOcean2.0, either with DTOcean1.0 still available or only DTOcean2.0. Is it possible to have DTOcean2.0 installed and running whilst having DTOcean1.0 (anaconda version) still on my computer or will DTOcean2.0 try to 'read' DTOcean1.0. In other words, will the two versions not interfere?
If they don't interfere, I will leave DTOCean1.0 on my computer and install DTOcean2.0 as indicated in the installation video (skipping the uninstall DTOcean1.0 step).
I hope this answers your questions, looking forward to your response!
Thanks!

**Comment by H0R5E** [comment]
OK, thanks for the clarification.

You should be OK to install DTOcean 2.0 using the wizard if you don't use the same installation directory as the hydrodynamics data package (which is probably installed into C:\DTOcean). If you choose the "Just me" option and install it into your home folder, then that will probably be fine.

**Comment by NoorvVelzen** [comment]
Thank you, I will try this!

**Comment by H0R5E** [comment]
No problem. Let me know if it works and then I can close the issue.

**Comment by NoorvVelzen** [comment]
I could install DTOcean2.0, thank you!

note: I had already uninstalled the Hydrodynamic Data package when going through the installation video, so I didn't encounter any problems with inference.

**Comment by H0R5E** [comment]
You will need the Hydrodynamics Data package to run your Anaconda version of DTOcean, so I would consider re-installing it. Glad everything else worked out for you.
