### ISSUE TITLE
How to modify database values

### ISSUE THREAD

**Issue by bhuvandto02** [DTOcean/dtocean#33]
Respected Sirs:

We have some queries in tool-DTOcean-Version-2.0, there are two solved examples we have worked on it, get results because of the tutorial. And we would like to have more knowledge on "pgAdmin4"
Question number 1: Can i upload the new input data in pgAdmin4 server created by me ? Is that possibile?
Question number 2: If yes, Would you send any tutorial link regarding pgAdmin4? or any qualified personnel help us out regarding this, I would really appreciate it.
Thanku

**Comment by H0R5E** [comment]
Hello,

There is a way of exporting and importing the database to a file structure that can be edited using the "Select Database Dialogue" as described here: [Load & Dump](https://dtocean.github.io/user/gui.html#load-dump). The structure of these files is described here: [Database Tables](https://dtocean.github.io/user/data_preparation.html#database-tables) and a general description of how the data is organised is found throughout the [Data Preparation](https://dtocean.github.io/user/data_preparation.html) section of the docs.

pgAdmin is a frontend to PostgreSQL, so if you want to interact with the database directly, I would suggest it's worth learning PostgreSQL first, i.e. [postgresqltutorial.com](https://www.postgresqltutorial.com/).

Good luck!

Mat
