### ISSUE TITLE
Variable File Manager: An AttributeError occurred: 'NoneType, object has no attribute 'keys' when saving (DTOcean 2.0's oldest bug)

### ISSUE THREAD

**Issue by KD379** [DTOcean/dtocean#37]
**Describe the bug**
An AttributeError occurred: 'NoneType, object has no attribute 'keys'
This error pops up whenever I try to save outputs 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Results
2. Go to 'variable file manager' for any results you want to save (save is already selected, load is not an option)
3. Click ellipsis (...) next to file path 
2020-12-08 15:39:54,483 - CRITICAL - dtocean_app.main - An AttributeError occurred: 'NoneType' object has no attribute 'keys'
2020-12-08 15:39:54,484 - CRITICAL - dtocean_app.main -   File "C:\Users\k-e-d\DTOcean\lib\site-packages\dtocean_app\widgets\central.py", line 305, in _set_path
    valid_exts = self._load_ext_dict.keys()

**Expected behaviour (if any)**
Expected to be able to save files in .csv format

**Screenshots**
![Screenshot 2020-12-08 154305](https://user-images.githubusercontent.com/72255727/101505314-21b9ad80-396c-11eb-8fef-56fe063d1e35.png)

**Version (please complete the following information):**
 - Which version of DTOcean are you using? DTOcean 2.0.0 (64bit WindowsPE)
- How did you install it? Installation wizard

**Comment by H0R5E** [comment]
Hi @KD379, you have discovered the oldest bug in DTOcean 2.0. You can fix it by replacing the file at:

 `C:\Users\k-e-d\DTOcean\lib\site-packages\dtocean_app\widgets\central.py`

with the file in the attached zip.

[central.zip](https://github.com/DTOcean/dtocean/files/5660329/central.zip)

**Comment by KD379** [comment]
Hi again @H0R5E. That works perfectly now, thanks!
