### ISSUE TITLE
Route not found - electrical module

### ISSUE THREAD

**Issue by davidbould** [DTOcean/dtocean#4]
A number of users reported that running the wave example from the DB results in a "route not found error" in the electrical module.  This error can be reproduced and also appears when using the tidal example database.

**Comment by H0R5E** [comment]
#1 is a duplicate of this issue.

**Comment by H0R5E** [comment]
It turns out that the bathymetry was not the issue here, but actually a bug in the electrical module that was 
hard setting the maximum gradient to zero.
