### ISSUE TITLE
Enviro Module - Incorrect CSV filename

### ISSUE THREAD

**Issue by davidbould** [DTOcean/dtocean#7]
The file "chemicalpollution_weighting.csv" in "C:\dtocean\Lib\site-packages\dtocean_environment\data\operation and maintenance" is incorrectly named "chemicalpollution_weighting.csv0000666" using the DTOcean installer.

Solution: rename file.

**Comment by H0R5E** [comment]
Confirmed. And on the 32bit installation I produced it as well. Be interesting to narrow down where this is happening. It doesn't appear in the Ananconda package, so its either Constructor or inno setup.

**Comment by H0R5E** [comment]
So, this appears to be the same as the issue reported here: ContinuumIO/anaconda-issues#3264

Essentially, there is an issue when constructor is trying to unpack a file path that is exactly 100 characters long. 

I think a short term fix for this will be to rename the effected folder, which should bring all the files below 100. The reference to the folder in the source code will also require modification.

**Comment by H0R5E** [comment]
Solved by https://github.com/DTOcean/dtocean-environment/pull/1
